import { connect } from 'react-redux';
import {
  loadSearchDataResources,
} from '../../../redux/actions/searchActions';
import Filters from './Filters';

const ReduxFilters = (() => {
  const mapStateToProps = (state) => ({
    // searchFilters: state.datasets.resourcesList,
    // sourceFilters: state.datasets.searchSourceResults,
    // selectedFilters: state.datasets.searchCriteria.resources_filter,
  });

  const mapDispatchToProps = {
    // onLoadSearchDataResources: loadSearchDataResources,
    onLoadSearchDataResources: {
      status: 'success',
      data: [
        {
          data_resource_id: 'All of Us',
          resource_name: 'All of Us',
          resource_type: 'Registry',
          description: "The All of Us Research Program is a historic effort to collect and study data from one million or more people living in the United States. The goal of the program is better health for all of us. Our mission is to accelerate health research and medical breakthroughs, enabling individualized prevention, treatment, and care for all of us. This mission is carried out through three connected focus areas that are supported and made possible by a team that maintains a culture built around the program's core values.",
          resource_uri: 'https://allofus.nih.gov/',
          data_content_type: 'Clinical',
          poc: 'Support Center',
          poc_email: 'help@joinallofus.org',
          api: '',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '02/23/2024',
        },
        {
          data_resource_id: 'BPC',
          resource_name: 'The Biopathology Center',
          resource_type: 'Biorepository',
          description: "The Biopathology Center (BPC) is part of the Abigail Wexner Research Institute at Nationwide Children's Hospital (AWRI) and provides a full range of services related to biospecimen procurement, banking, processing, and distribution. The BPC is accredited by the College of American Pathologists Biorepository Accreditation Program (CAP BAP) and houses numerous biospecimen collection efforts, including the biorepositories of the National Cancer Institute (NCI) funded Children's Oncology Group, NRG Oncology-Columbus (formerly the GOG Tissue Bank), and SWOG. Also part of the BPC are the NCI-funded Pediatric Division of the Cooperative Human Tissue Network, and the Biospecimen Core Resource of the Center for Cancer Genomics (CCG), as well as numerous biospecimen collections sponsored by funded NCH investigators. Today, more than 4 million biospecimens are stored by the BPC using various storage modalities, including liquid nitrogen and -80 C mechanical freezers.",
          resource_uri: 'https://www.nationwidechildrens.org/research/areas-of-research/biopathology-center',
          data_content_type: 'Biospecimens',
          poc: 'Nilsa Ramirez, MD',
          poc_email: 'bpc@nationwidechildrens.org',
          api: '',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 0,
          datasets_total: 6,
          data_update_date: '08/03/2023',
        },
        {
          data_resource_id: 'BTB',
          resource_name: 'Swedish Childhood Tumor Biobank',
          resource_type: 'Biorepository',
          description: 'The Swedish Childhood Tumor Biobank (BTB) is a nonprofit national infrastructure for collecting tissue samples and genomic data from pediatric patients diagnosed with central nervous system (CNS) and other solid tumors. The BTB is built on a multidisciplinary network established to provide the scientific community with standardized biospecimens and genomic data, thereby improving knowledge of the biology, treatment, and outcome of childhood tumors. As of 2022, over 1,100 fresh-frozen tumor samples are available for researchers.',
          resource_uri: 'https://ki.se/forskning/barntumorbanken',
          data_content_type: 'Biospecimens',
          poc: 'Johanna Sandgren',
          poc_email: 'johanna.sandgren@ki.se',
          api: '',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '08/03/2023',
        },
        {
          data_resource_id: 'CancerModels.Org',
          resource_name: 'CancerModels.Org',
          resource_type: 'Catalog',
          description: 'Patient-derived cancer models have become an essential tool in both cancer research, drug development and preclinical studies. Each model type - PDX, organoid and cell line - offers unique advantages and is better suited for specific research areas. Researchers, clinicians, bioinformaticians and analytical tool developers face the challenge of navigating a complex landscape to find suitable models and associated data across multiple commercial and academic resources without the benefit of shared data standards or interoperable data. CancerModels.Org aims to solve this problem by providing harmonized and integrated model attributes to support consistent searching across the originating resources.',
          resource_uri: 'https://www.cancermodels.org/',
          data_content_type: 'Genomics/Omics,Clinical,Xenograft,Cell Lines',
          poc: 'CancerModels.Org Mailbox',
          poc_email: 'info@cancermodels.org',
          api: '',
          pediatric_specific: 0,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '05/20/2024',
        },
        {
          data_resource_id: 'cBioPortal',
          resource_name: 'cBioPortal for Cancer Genomics',
          resource_type: 'Data Repository',
          description: 'The cBioPortal for Cancer Genomics is a resource for interactive exploration of multidimensional cancer genomics data sets. The goal of cBioPortal is to significantly lower the barriers between complex genomic data and cancer researchers by providing rapid, intuitive, and high-quality access to molecular profiles and clinical attributes from large-scale cancer genomics projects, and therefore to empower researchers to translate these rich data sets into biologic insights and clinical applications.',
          resource_uri: 'https://www.cbioportal.org/',
          data_content_type: 'Genomics/Omics,Clinical',
          poc: 'cBioPortal Mailbox',
          poc_email: 'cbioportal@googlegroups.com',
          api: 'https://docs.cbioportal.org/web-api-and-clients/',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 0,
          datasets_total: 28,
          data_update_date: '05/29/2024',
        },
        {
          data_resource_id: 'CBTRUS',
          resource_name: 'Central Brain Tumor Registry of the United States',
          resource_type: 'Registry',
          description: 'The Central Brain Tumor Registry of the United States (CBTRUS) is a not-for-profit research corporation, recognized by the international research community as the premier resource for annual histology-specific statistical information for all primary brain and other CNS tumors in the United States. The CBTRUS analytic database has been developed by compiling data from central (state) cancer registries, the District of Columbia, and Puerto Rico that include information on both malignant and non-malignant primary brain and other CNS tumors.',
          resource_uri: 'https://cbtrus.org/',
          data_content_type: 'Clinical',
          poc: 'Jill S. Barnholtz-Sloan, Ph.D.',
          poc_email: 'jill.barnholtz-sloan@nih.gov',
          api: '',
          pediatric_specific: 0,
          analytics: 0,
          visualization: 0,
          datasets_total: 3,
          data_update_date: '03/20/2024',
        },
        {
          data_resource_id: 'CCDI',
          resource_name: 'Childhood Cancer Data Initiative',
          resource_type: 'Program',
          description: "NCI's Childhood Cancer Data Initiative (CCDI) is building a community centered around childhood cancer care and research data. Through enhanced data sharing, we can improve our understanding of cancer biology to improve preventive measures, treatment, quality of life, and survivorship, as well as ensure that researchers learn from every child with cancer. While childhood cancers represent the leading cause of death in children over the age of 1, they are collectively rare, comprising about 1%-3% of cancers diagnosed annually in the United States. Information on diagnosis, treatment, and outcomes is often stored at the hospital or institution where a child is treated, making it difficult to answer scientific questions about childhood cancer. Sharing clinical care and research data generated by children's hospitals, clinics, or networks broadly with the community can help us learn faster and on a scale much larger than any single institution caring for children can learn on its own.",
          resource_uri: 'https://www.cancer.gov/research/areas/childhood/childhood-cancer-data-initiative',
          data_content_type: 'Genomics/Omics,Clinical',
          poc: 'CCDI Mailbox',
          poc_email: 'NCIChildhoodCancerDataInitiative@mail.nih.gov',
          api: 'https://cgc.sbgenomics.com/datasets/file-repository',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 0,
          datasets_total: 16,
          data_update_date: '07/22/2024',
        },
        {
          data_resource_id: 'CCSS',
          resource_name: 'Childhood Cancer Survivor Study',
          resource_type: 'Program',
          description: "It has been shown that, to varying degrees, long-term survivors of childhood cancer are at risk of developing second cancers and of experiencing organ dysfunction, reduced growth and development, decreased fertility, and early death. The degree of risk of late effects may be influenced by various treatment-related factors such as the intensity, duration, and timing of therapy, as well as by individual characteristics such as the type of cancer diagnosis, the person's sex and age at the time of treatment, and genetic factors as indicated by for example, family history of cancer. The catalyzing goal of the Childhood Cancer Survivor Study (CCSS) was to assemble a cohort of survivors sufficiently large and diverse enough to enable investigators to characterize the experience of participants regarding these and other delayed effects of treatment. Further, investigators hoped to be able to gather information about the health-related behaviors and patterns of medical care use of survivors in order to facilitate the development of prevention strategies and the assessment of follow-up needs.",
          resource_uri: 'https://ccss.stjude.org/',
          data_content_type: 'Genomics/Omics,Clinical',
          poc: 'Gregory T. Armstrong, M.D., MSCE.',
          poc_email: 'greg.armstrong@stjude.org',
          api: 'https://ccss.stjude.org/develop-a-study/process-overview.html',
          pediatric_specific: 1,
          analytics: 1,
          visualization: 1,
          datasets_total: 1,
          data_update_date: '09/28/2023',
        },
        {
          data_resource_id: 'CEDCD',
          resource_name: 'Cancer Epidemiology Descriptive Cohort Database',
          resource_type: 'Catalog',
          description: 'The Cancer Epidemiology Descriptive Cohort Database (CEDCD) contains descriptive information about cohort studies that follow groups of persons over time for cancer incidence, mortality, and other health outcomes. The CEDCD is a searchable database that contains general study information (e.g., eligibility criteria and size), the type of data collected at baseline, cancer sites, number of participants diagnosed with cancer, and biospecimen information. All data included in this database are aggregated for each cohort; there are no individual level data. The goal of the CEDCD is to facilitate collaboration and highlight the opportunities for research within existing cohort studies.',
          resource_uri: 'https://cedcd.nci.nih.gov/home',
          data_content_type: 'Clinical',
          poc: 'CEDCD Contact Form',
          poc_email: 'https://cedcd.nci.nih.gov/contact',
          api: '',
          pediatric_specific: 0,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '07/10/2024',
        },
        {
          data_resource_id: 'CGC',
          resource_name: 'Cancer Genomics Cloud',
          resource_type: 'Analytic Tool',
          description: 'The Cancer Genomics Cloud (CGC), powered by Seven Bridges and funded by the NCI, is a flexible cloud platform that enables analysis, storage, and computation of large cancer datasets. The CGC provides a user-friendly portal to access and analyze cancer data where it lives. With the CGC, any user with an account can easily access petabytes of cancer data, share it, analyze and use the computational power of the cloud without having to learn how to program and get familiar with several different data portals.',
          resource_uri: 'https://cgc.sbgenomics.com/home',
          data_content_type: 'Genomics/Omics',
          poc: 'CGC Team',
          poc_email: 'cgc@sbgenomics.com',
          api: '',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 4,
          data_update_date: '05/22/2024',
        },
        {
          data_resource_id: 'CGCI',
          resource_name: 'Cancer Genome Characterization Initiative',
          resource_type: 'Program',
          description: 'The Cancer Genome Characterization Initiative (CGCI) uses molecular characterization to uncover distinct features of rare cancers. Current projects perform comprehensive molecular cataloging of HIV+ and other rare adult and pediatric cancers. The CGCI Data Matrix is a high-level catalog of data generated by the Initiative, with links to the sites where the controlled access data are hosted. The projects described on CGCI pages include Burkitt Lymphoma, HIV+ Tumor Molecular Characterization Project, Medulloblastoma-Complete, and Non-Hodgkin Lymphoma-Complete.',
          resource_uri: 'https://www.cancer.gov/ccg/research/genome-sequencing/cgci',
          data_content_type: 'Genomics/Omics,Imaging,Clinical',
          poc: 'Center for Cancer Genomics',
          poc_email: 'NCICCGenomics@mail.nih.gov',
          api: 'https://gdc.cancer.gov/developers/gdc-application-programming-interface-api',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 0,
          datasets_total: 2,
          data_update_date: '07/23/2024',
        },
        {
          data_resource_id: 'Childhood Cancer Repository',
          resource_name: 'Childhood Cancer Repository',
          resource_type: 'Data Repository',
          description: "The Childhood Cancer Repository, powered by Alex's Lemonade Stand Foundation, is a resource laboratory of the Children's Oncology Group. The laboratory is located at Texas Tech University Health Sciences Center in Lubbock, TX, and is under the direction of C Patrick Reynolds, MD PhD. The repository is generously supported by Alex's Lemonade Stand Foundation. With the exception of legacy cell lines established many years ago, all cell lines and PDXs banked in cccells.org are obtained via clinical protocols (mostly COG) with informed consent/assent. Patient confidentiality is a prime concern and cell lines and PDXs receive designators that enables linkage to key data but not directly to any patient. The one exception to this are those cell lines and PDXs established from patients at post-mortem, which (if requested by the parents) are provided a unique name of the parents' choosing. The goal of the repository is to provide validated cell lines and PDXs from childhood cancers to all investigators seeking to carry out biological and pre-clinical therapeutic studies of childhood cancer. Every cell line or PDX provided by the repository is validated as to patient of origin by short tandem repeat (STR) assay, and to be free of mycoplasma and EBV. PDXs are validated to be free of a panel of viral pathogens as required by most animal use committees. Cell lines and PDXs are validated to be able to grow continuously and be sub-passable for additional studies. The repository maintains a searchable STR database to facilitate validation of cell line and PDX molecular identity by any investigator. Thus, the repository enables all investigators studying childhood cancer to share the same validated models so that data obtained are robust and can be compared between laboratories.",
          resource_uri: 'https://cccells.org/',
          data_content_type: 'Xenograft,Cell Lines',
          poc: 'Childhood Cancer Repository Mailbox',
          poc_email: 'https://cccells.org/contact.php',
          api: '',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '06/17/2024',
        },
        {
          data_resource_id: 'CIViC',
          resource_name: 'Clinical Interpretations of Variants in Cancer',
          resource_type: 'Knowledgebase',
          description: 'Precision medicine refers to the use of prevention and treatment strategies that are tailored to the unique features of each individual and their disease. In the context of cancer this might involve the identification of specific variants shown to predict response to a targeted therapy. The biomedical literature describing associations between genetic variants and clinically relevant outcomes is large and growing rapidly. Currently variant interpretations exist largely in private or encumbered databases resulting in extensive repetition of effort. Effective precision medicine requires this information to be centralized, debated, and interpreted for application in a clinical setting. CIViC is an open access, open source, community-driven web resource for Clinical Interpretation of Variants in Cancer, available online at civicdb.org. Our goal is to enable precision medicine by providing an educational forum for dissemination of knowledge and active discussion of the clinical significance of cancer genome alterations. For more details and to cite CIViC please refer to the CIViC publication in Nature Genetics.',
          resource_uri: 'https://civicdb.org/',
          data_content_type: 'Clinical',
          poc: 'Malachi Griffith, PhD ; Obi Griffith, PhD',
          poc_email: 'mgriffith@wustl.edu;obigriffith@wustl.edu',
          api: 'https://docs.civicdb.org/en/latest/api.html',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 1,
          data_update_date: '03/18/2024',
        },
        {
          data_resource_id: 'COG',
          resource_name: "Children's Oncology Group",
          resource_type: 'Catalog',
          description: "The Children's Oncology Group (COG) is the world's largest organization devoted exclusively to childhood and adolescent cancer research. The COG unites more than 10,000 experts in childhood cancer at more than 200 leading children's hospitals, universities, and cancer centers across the world in the fight against childhood cancer. Today, more than 90% of 16,000 children and adolescents diagnosed with cancer each year in the United States are cared for at COG member institutions. COG's unparalleled collaborative efforts provide the information and support needed to answer important clinical questions in the fight against cancer.\r\n\r\nThe Children's Oncology Group has nearly 100 active clinical trials open at any given time. These trials include front-line treatment for many types of childhood cancers, studies aimed at determining the underlying biology of these diseases, and trials involving new and emerging treatments, supportive care, and survivorship. COG research has turned children's cancer from a virtually incurable disease 50 years ago to one with a combined 5-year survival rate of 80% today.  Our goal is to cure all children and adolescents with cancer, reduce the short and long-term complications of cancer treatments, and determine the causes and find ways to prevent childhood cancer.",
          resource_uri: 'https://childrensoncologygroup.org/',
          data_content_type: 'Clinical',
          poc: 'Douglas S. Hawkins, MD',
          poc_email: 'doug.hawkins@seattlechildrens.org',
          api: '',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '12/18/2023',
        },
        {
          data_resource_id: 'CRI iAtlas',
          resource_name: 'Cancer Research Institute iAtlas',
          resource_type: 'Analytic Tool',
          description: 'The Cancer Research Institute (CRI) iAtlas is an interactive web platform and a set of analytic tools for studying interactions between tumors and the immune microenvironment. These tools allow researchers to explore associations between a variety of genomic characterizations of immune response, clinical phenotypes, germline genetics, and response to immunotherapy. Immune checkpoint inhibitor analysis modules allow for interactive exploration of the relationship between possible biomarkers of immune response and the outcome of response to checkpoint blockade, by direct comparison and using multivariable statistical models. Underlying these modules is a harmonization of primary sequencing data from 12 immuno-oncology trials with genomics data and matched clinical data available in the public domain. iAtlas also allows researchers to identify how tumor-intrinsic alterations, including mutations, copy-number alterations, and neoantigens relate to the immune microenvironment as evidenced in cancer genomic studies.',
          resource_uri: 'https://cri-iatlas.org/',
          data_content_type: 'Genomics/Omics,Clinical',
          poc: 'CRI iAtlas Team',
          poc_email: 'support@cri-iatlas.org',
          api: '',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 1,
          data_update_date: '05/23/2024',
        },
        {
          data_resource_id: 'dbGaP',
          resource_name: 'The database of Genotypes and Phenotypes',
          resource_type: 'Data Repository',
          description: 'The database of Genotypes and Phenotypes (dbGaP) was developed to archive and distribute the data and results from studies that have investigated the interaction of genotype and phenotype in humans.',
          resource_uri: 'https://www.ncbi.nlm.nih.gov/gap/',
          data_content_type: 'Genomics/Omics,Clinical',
          poc: 'Mike Feolo',
          poc_email: 'feolo@ncbi.nlm.nih.gov',
          api: '',
          pediatric_specific: 0,
          analytics: 0,
          visualization: 1,
          datasets_total: 70,
          data_update_date: '05/08/2024',
        },
        {
          data_resource_id: 'DepMap',
          resource_name: 'Cancer Dependency Map',
          resource_type: 'Analytic Tool',
          description: 'The goal of the Dependency Map (DepMap) portal is to empower the research community to make discoveries related to cancer vulnerabilities by providing open access to key cancer dependencies analytical and visualization tools.',
          resource_uri: 'https://depmap.org/portal/',
          data_content_type: 'Genomics/Omics,Cell Lines',
          poc: 'DepMap Contact Email',
          poc_email: 'depmap@broadinstitute.org',
          api: null,
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 1,
          data_update_date: '10/24/2023',
        },
        {
          data_resource_id: 'Fibroregistry',
          resource_name: 'Fibrolamellar Registry',
          resource_type: 'Registry',
          description: "The Fibrolamellar Registry is run by patients with a rare pediatric/ young adult liver cancer called fibrolamellar hepatocellular carcinoma, and their loved ones. It's a place to both share information on this disease and gather it, as we believe pooling our knowledge will bring us better diagnostics, treatments and, one day, a cure. The Registry first launched in October of 2016. Our survey is approved as a scientific study by the WCG Institutional Review Board and we belong to the REDCap Consortium, which is supported by the National Institutes of Health. We have been awarded grants by the Rally Foundation for Childhood Cancer Research, the Richard Lounsbery Foundation and others, and have been part of the National Patient-Centered Clinical Research Network (PCORNET) as members of the Genetic Alliance. We are partners with the Fibrolamellar Tissue Repository at Rockefeller University, which stores fibrolamellar tissue samples, making the Registry data twice as useful. The Registry is a non-profit organization.",
          resource_uri: 'https://fibroregistry.org/',
          data_content_type: 'Clinical',
          poc: 'Sanford Simon',
          poc_email: 'Sanford.Simon@rockefeller.edu',
          api: '',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '02/23/2024',
        },
        {
          data_resource_id: 'GDC',
          resource_name: 'Genomic Data Commons',
          resource_type: 'Data Repository',
          description: "The National Cancer Institute's (NCI's) Genomic Data Commons (GDC) is a data sharing platform that promotes precision medicine in oncology. It is not just a database or a tool; it is an expandable knowledge network supporting the import and standardization of genomic and clinical data from cancer research programs. The GDC contains NCI-generated data from some of the largest and most comprehensive cancer genomic datasets, including The Cancer Genome Atlas (TCGA) and Therapeutically Applicable Research to Generate Effective Therapies (TARGET). These datasets have been processed using a common set of bioinformatics pipelines, so that the data can be directly compared.",
          resource_uri: 'https://portal.gdc.cancer.gov/',
          data_content_type: 'Genomics/Omics,Clinical,Xenograft',
          poc: 'Zhining Wang',
          poc_email: 'zhining.wang@nih.gov',
          api: 'https://docs.gdc.cancer.gov/API/Users_Guide/Getting_Started/',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 13,
          data_update_date: '06/17/2024',
        },
        {
          data_resource_id: 'GENIE',
          resource_name: 'Genomics Evidence Neoplasia Information Exchange',
          resource_type: 'Data Repository',
          description: 'Precision medicine requires an end-to-end learning health care system, wherein the treatment decisions for patients are informed by the prior experiences of similar patients. Oncology is currently leading the way in precision medicine because the genomic and other molecular characteristics of patients and their tumors are routinely collected at scale. A major challenge to realizing the promise of precision medicine is that no single institution is able to sequence and treat sufficient numbers of patients to improve clinical-decision making independently. To overcome this challenge, the AACR launched Project GENIE (Genomics Evidence Neoplasia Information Exchange). AACR Project GENIE is a publicly accessible cancer registry of real-world clinico-genomic data assembled through data sharing between 19 leading international cancer centers. Through the efforts of strategic partners Sage Bionetworks and cBioPortal, the registry aggregates, harmonizes, and links clinical-grade, next-generation cancer genomic sequencing data with clinical outcomes obtained during routine medical practice from nearly every cancer patient treated at these institutions. The consortium and its activities are driven by openness, transparency, and inclusion, ensuring that the project output remains accessible to the global cancer research community for the benefit of all. We see the GENIE data providing another knowledge turn in the virtuous cycle of research, accelerating the pace of drug discovery, improving clinical trial design, and ultimately benefiting cancer patients globally.',
          resource_uri: 'https://www.aacr.org/professionals/research/aacr-project-genie/',
          data_content_type: 'Genomics/Omics,Clinical',
          poc: 'GENIE Mailbox',
          poc_email: 'info@aacrgenie.org',
          api: '',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 0,
          datasets_total: 7,
          data_update_date: '04/19/2024',
        },
        {
          data_resource_id: 'GEO',
          resource_name: 'Gene Expression Omnibus',
          resource_type: 'Data Repository',
          description: 'GEO is a public functional genomics data repository supporting MIAME-compliant data submissions. Array- and sequence-based data are accepted. Tools are provided to help users query and download experiments and curated gene expression profiles.',
          resource_uri: 'https://www.ncbi.nlm.nih.gov/geo/',
          data_content_type: 'Genomics/Omics',
          poc: 'GEO Mailbox',
          poc_email: 'geo@ncbi.nlm.nih.gov',
          api: 'https://www.ncbi.nlm.nih.gov/geo/info/geo_paccess.html',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 0,
          datasets_total: 24,
          data_update_date: '05/28/2024',
        },
        {
          data_resource_id: 'HCMI',
          resource_name: 'Human Cancer Models Initiative',
          resource_type: 'Catalog',
          description: "The Human Cancer Models Initiative (HCMI) is an international collaboration between the NCI, Cancer Research UK, Wellcome Sanger Institute, and foundation Hubrecht Organoid Technology. The goal of HCMI is to create up to 1,000 patient-derived Next-generation Cancer Models such as organoids, conditionally reprogrammed cells, neurospheres, or optimal growth condition models as a community resource. HCMI aims to provide the models' case-associated data, which includes quality-checked clinical, biospecimen, and molecular characterization data from the models, the tissues from which they were derived, and normal tissues, when available. Available harmonized data are accessible through the NCI's Genomic Data Commons (GDC) or the European Bioinformatics Institute. The HCMI uses current culture techniques to develop cancer models for translational cancer research and other experiments.",
          resource_uri: 'https://ocg.cancer.gov/programs/HCMI',
          data_content_type: 'Genomics/Omics,Clinical',
          poc: 'Office of Cancer Genomics',
          poc_email: 'ocg@mail.nih.gov',
          api: '',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 1,
          data_update_date: '09/06/2023',
        },
        {
          data_resource_id: 'HitWalker2',
          resource_name: 'HitWalker2',
          resource_type: 'Analytic Tool',
          description: 'The lack of integrated visualization and prioritization frameworks to guide interpretation and facilitate discovery is a potential bottleneck for precision medicine, systems genetics and other studies. To address this we have developed an interactive, reproducible, web-based prioritization approach that builds on our earlier work. HitWalker2 is highly flexible and can utilize many data types and prioritization methods based upon available data and desired questions, allowing it to be utilized in a diverse range of studies such as cancer, infectious disease and psychiatric disorders.',
          resource_uri: 'https://github.com/biodev/HitWalker2',
          data_content_type: 'Genomics/Omics',
          poc: 'Beth Wilmot',
          poc_email: 'wilmotb@ohsu.edu',
          api: '',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 1,
          data_update_date: '01/19/2024',
        },
        {
          data_resource_id: 'HTAN',
          resource_name: 'Human Tumor Atlas Network',
          resource_type: 'Program',
          description: 'An NCI-funded Cancer Moonshot initiative to construct 3-dimensional atlases of the dynamic cellular, morphological, and molecular features of human cancers as they evolve from precancerous lesions to advanced disease.',
          resource_uri: 'https://humantumoratlas.org/',
          data_content_type: 'Genomics/Omics,Imaging,Clinical',
          poc: 'Kristina A. Cole., M.D.,Ph.D.',
          poc_email: 'colek@email.chop.edu',
          api: '',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '12/06/2023',
        },
        {
          data_resource_id: 'iCat',
          resource_name: 'Individualized Cancer Therapy Study',
          resource_type: 'Project',
          description: 'Some cancer-causing gene alterations (such as mutations or copy number alterations) are common or occur repeatedly in different types of cancers. For some of these alterations there are drugs, called targeted drugs that specifically counteract the alteration. In certain cancer types, these targeted drugs are very effective at fighting the cancer. A tumor specimen that has been obtained previously or is planned to be obtained as part of clinical care will be used to perform tumor profiling. Additional procedures to obtain tumor will not be performed. An expert panel will review the results of the tumor profiling tests and determine whether a cancer-causing alteration is present and whether an individualized treatment recommendation can be made. If consent to sharing of the tumor profiling results and individualized treatment recommendation is provided then a study physician will discuss the profiling results and the individualized treatment recommendation with the primary oncologist. In addition, the primary oncologist will receive a letter detailing the tumor profiling results and the individualized treatment recommendation.',
          resource_uri: 'https://doi.org/10.1001/jamaoncol.2015.5689',
          data_content_type: 'Clinical',
          poc: 'Katherine A. Janeway, MD',
          poc_email: 'katherine_janeway@dfci.harvard.edu',
          api: '',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '07/22/2024',
        },
        {
          data_resource_id: 'IDC',
          resource_name: 'NCI Imaging Data Commons',
          resource_type: 'Data Repository',
          description: "NCI Imaging Data Commons (IDC) is a cloud-based repository of publicly available cancer imaging data co-located with the analysis and exploration tools and resources. IDC is a node within the broader NCI Cancer Research Data Commons (CRDC) infrastructure that provides secure access to a large, comprehensive, and expanding collection of cancer research data. All data hosted by IDC will be available publicly. The current content of IDC is populated using the radiology collections from The Cancer Imaging Archive (TCIA) , as well as data collected by other major NCI initiatives, such as TCGA, CPTAC, NLST, and HTAN. IDC does not perform de-identification of images but will accept data de-identified by TCIA or other Data Coordinating Centers that are approved by NCI Security. IDC provides access to the data standardized using the Digital Imaging and Communication in Medicine (DICOM) standard. IDC collaborates with the projects generating the data to harmonize alternative formats into DICOM representation. Its content includes not only images, but also image annotations and analysis results, and is linked using common identifiers to the other types of cancer data, such as proteomics and genomics datasets in the Cancer Research Data Commons (CRDC). Access to the data is supported using standard interfaces. Given the IDC's role as an imaging data science platform, a major focus is on establishing best practices for imaging research. In this regard, a key role of IDC is in preparing and adapting commonly used tools for image analysis to be run on cloud environments with IDC-hosted datasets. Summarized derived data from analyses previously run will be associated with imaging data on IDC for ease of use by the research community.",
          resource_uri: 'https://portal.imaging.datacommons.cancer.gov/',
          data_content_type: 'Imaging',
          poc: 'IDC Mailbox',
          poc_email: 'support@canceridc.dev',
          api: '',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 1,
          data_update_date: '04/18/2024',
        },
        {
          data_resource_id: 'ITCC P4',
          resource_name: 'Innovative Therapies for Children with Cancer Paediatric Preclinical Proof-of-Concept Platform',
          resource_type: 'Program',
          description: "Innovative Therapies for Children with Cancer Paediatric Preclinical Proof-of-Concept Platform (ITCC-P4) is a newly formed public-private partnership supported by the European consortium \"Innovative Medicines Initiative\" (IMI). The consortium with currently 26 partners from 10 countries aims to establish 420 new patient-derived preclinical models of high-risk pediatric tumors which will be fully characterized (molecularly, immunologically, pharmacologically and clinically well-annotated) and to build a sustainable comprehensive platform to use these models for drug testing. It brings together many of Europe's most distinguished academic and clinical research institutions, well established Small-to-Medium sized Enterprises (SMEs), members of the European Biopharmaceutical Enterprises (EBE) and the members of the European Federation of Pharmaceutical Industries and Associations (EFPIA) thus providing a unique setting to improve patient outcomes by introducing new and effective medicines in standard of care of young people still dying of these rare cancers.",
          resource_uri: 'https://www.itccp4.eu/',
          data_content_type: 'Genomics/Omics,Clinical,Xenograft',
          poc: 'German Cancer Research Center (DKFZ)',
          poc_email: 'itccp4@kitz-heidelberg.de',
          api: '',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '06/17/2024',
        },
        {
          data_resource_id: 'JAX PDX',
          resource_name: 'The Jackson Laboratory PDX Models',
          resource_type: 'Data Repository',
          description: "Patient-Derived Xenografts (PDX) are generated through the engraftment and passaging of tissue or cells from a patient's tumor into an immunodeficient or humanized mouse host. PDX models are an in vivo platform for cancer biology research and for pre-clinical testing of cancer drug efficacy. The Mouse Models of Human Cancer Database provides access to information on hundreds of PDX models distributed by The Jackson Laboratory (JAX). Researchers can search for JAX PDXs by such criteria as primary cancer site, diagnosis, genomic characteristics of engrafted tumors, and PDX dosing study results.",
          resource_uri: 'https://www.jax.org/jax-mice-and-services/in-vivo-pharmacology/oncology-services/pdx-tumors',
          data_content_type: 'Genomics/Omics,Clinical,Xenograft',
          poc: 'Debra M. Krupke, MS; Dale A. Begley, PhD',
          poc_email: 'http://www.informatics.jax.org/mgihome/support/mgi_inbox.shtml',
          api: '',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '04/12/2024',
        },
        {
          data_resource_id: 'Kids First Data Resource',
          resource_name: 'Kids First Data Resource',
          resource_type: 'Data Repository',
          description: 'The goal of the Gabriella Miller Kids First Pediatric Research Program (Kids First) is to help researchers uncover new insights into the biology of childhood cancer and structural birth defects, including the discovery of shared genetic pathways between these disorders.',
          resource_uri: 'https://portal.kidsfirstdrc.org/login',
          data_content_type: 'Genomics/Omics,Imaging,Clinical',
          poc: 'Allison Heath',
          poc_email: 'heathap@email.chop.edu',
          api: 'https://portal.kidsfirstdrc.org/login',
          pediatric_specific: 1,
          analytics: 1,
          visualization: 1,
          datasets_total: 12,
          data_update_date: '07/01/2024',
        },
        {
          data_resource_id: 'M3Cs',
          resource_name: 'MicroRNA Childhood Cancer Catalog Version 2.0',
          resource_type: 'Catalog',
          description: "M3Cs version 2.0 is an upgrade of M3Cs. M3Cs Version 2.0 is the first specialized microRNA platform in childhood cancer that introduced 'clinical validity' for all microRNAs included in M3Cs 'Clinical Domain' using 'Consensus of M3Cs Standardized Clinical Validity Framework 2024 Version 1.0' which was developed by a panel of experts in the field. M3Cs Version 2.0 utilized digital innovation, as a primer for the introduction of translational bioinformatics approaches and data-driven decision-making, to deliver a unique value microRNA platform. Digital innovation fosters an agile and adaptive organizational strategy with the help of data-driven insights that were needed by M3Cs for evidence synthesis and implementation to move forward from translational bioinformatics to clinical validity toward clinical utility/application in childhood cancer. It encourages journal editors, reviewers, as well as researchers to standardize miRNA clinical publications according to the United Nations SDGs ensuring healthy lives and promoting well-being at all ages are essential to sustainable development. M3Cs Version 2.0 seeks to contribute to the achievement of SDG3 (Good Health and Well-Being) , SDG9 (Innovation and Infrastructure) , and SDG17 (Partnerships) by providing high-quality specialized microRNA platform in translational bioinformatics, evidence synthesis, and clinical validity for childhood cancer diseases. M3Cs Version 2.0 is a standard model that can be applied in other microRNA platforms of various diseases to promote their clinical utility.",
          resource_uri: 'https://m3cs.shinyapps.io/M3CS-V2/',
          data_content_type: 'Genomics/Omics,Clinical',
          poc: 'Wafaa M. Rashed, PhD',
          poc_email: 'mirna.childhood.cancer.catalog@gmail.com',
          api: '',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 1,
          datasets_total: 1,
          data_update_date: '01/17/2024',
        },
        {
          data_resource_id: 'MTP',
          resource_name: 'Molecular Targets Platform',
          resource_type: 'Knowledgebase',
          description: "The Molecular Targets Platform is a National Cancer Institute (NCI) instance of the Open Target Platfom with a focus on pediatric cancer data. This tool allows users to browse and identify associations between molecular targets, diseases, and drugs. The Molecular Targets Platform builds upon the data and functionality of the Open Targets Platform while also including the FDA Pediatric Molecular Target Lists (FDA PMTL) and analyses of pediatric oncology datasets from the Open Pediatric Cancer (OpenPedCan) project at the Children's Hospital of Philadelphia. As the project matures, new pediatric cancer data and additional functionality will be added to the Molecular Targets Platform.",
          resource_uri: 'https://moleculartargets.ccdi.cancer.gov/',
          data_content_type: 'Clinical',
          poc: null,
          poc_email: 'ncichildhoodcancerdatainitiative@mail.nih.gov',
          api: '',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 1,
          data_update_date: '08/04/2022',
        },
        {
          data_resource_id: 'MyPART',
          resource_name: 'MyPART',
          resource_type: 'Program',
          description: 'MyPART is the My Pediatric and Adult Rare Tumor network. It is a group of scientists, patients, family members, advocates, and healthcare providers who want to help find treatments for rare cancers. We are working on childhood, teen, and young adult solid rare tumors that have no cures. We think that working as a team will help us find treatments for rare cancers faster.',
          resource_uri: 'https://www.cancer.gov/pediatric-adult-rare-tumor/',
          data_content_type: 'Genomics/Omics',
          poc: null,
          poc_email: 'NCICCRRareTumors@mail.nih.gov ',
          api: '',
          pediatric_specific: 0,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '02/24/2024',
        },
        {
          data_resource_id: 'NCCB',
          resource_name: 'Norwegian Childhood Cancer Biobank',
          resource_type: 'Biorepository',
          description: 'The Norwegian Childhood Cancer Biobank (NCCB) is a prospective biobank including infants, children, and adolescents from 0 to 18 years of age diagnosed with cancer in Norway. The overall aim of the NCCB is to stimulate and facilitate basic and translational research within childhood cancer through a national pipeline for biobanking tumor, microbiotic, and germline tissue at all regional childhood cancer departments and from all children with newly diagnosed cancer in Norway, providing the basis for advanced childhood cancer research on a national and international basis.',
          resource_uri: 'https://www.ous-research.no/childhoodcancerbiobank/',
          data_content_type: 'Biospecimens',
          poc: 'Monica C. Munthe-Kaas',
          poc_email: 'uxmomu@ous-hf.no',
          api: '',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '08/03/2023',
        },
        {
          data_resource_id: 'NCTN',
          resource_name: 'NCTN Navigator',
          resource_type: 'Catalog',
          description: "NCI's National Clinical Trials Network (NCTN) is a collection of organizations and clinicians that coordinates and supports cancer clinical trials at more than 2,200 sites across the United States, Canada, and internationally. NCTN provides the infrastructure for NCI-funded treatment and primary advanced imaging trials to improve the lives of people with cancer. NCTN clinical trials help to establish new standards of care, set the stage for approval of new therapies by the Food and Drug Administration, test new treatment approaches, and validate new biomarkers. The NCTN Navigator allows Investigators to query from available biospecimens, and to request biospecimens using the Letter of Intent (LOI) form. The request will go through a feasibility review process using one or more Feasibility Reports. After the Feasibility Report(s) are complete, the Investigator will be able to complete a Proposal form . After the Proposal form is submitted to the Front Door Service (FDS) Concierge for review, it will go through a scientific review process, which will include a Core Correlative Sciences Committee (CCSC) review decision.",
          resource_uri: 'https://navigator.ctsu.org/navigator/',
          data_content_type: 'Clinical',
          poc: 'Front Door Service Concierge',
          poc_email: 'navigatorcontact@imsweb.com',
          api: '',
          pediatric_specific: 0,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '07/03/2024',
        },
        {
          data_resource_id: 'NICD',
          resource_name: 'National Institute for Communicable Diseases - National Cancer Registry',
          resource_type: 'Registry',
          description: 'The South African National Cancer Registry (NCR) has been conducting national pathology-based cancer registration since its establishment in 1986. Data (demographic, clinical and reporting source) on cancer cases diagnosed either by histology, cytology, bone marrow aspirate and or trephine are submitted to NCR from both private and public laboratories across South Africa. The collected data is cleaned, analysed and reported in the annual cancer incidence report by sex, age and population groups. The national pathology-based cancer registry has been the primary source of cancer statistics for the country and has played a critical role in the development of cancer prevention and control policy for the country.',
          resource_uri: 'https://www.nicd.ac.za/centres/national-cancer-registry/',
          data_content_type: 'Clinical',
          poc: 'Contact Form',
          poc_email: 'https://www.nicd.ac.za/contact-us/',
          api: '',
          pediatric_specific: 0,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '04/25/2024',
        },
        {
          data_resource_id: 'Oncogenomics',
          resource_name: 'Oncogenomics',
          resource_type: 'Data Repository',
          description: 'The mission of the Oncogenomics Section is to harness the power of high throughput genomic and proteomic methods to improve the outcome of children with high-risk metastatic, refractory, and recurrent cancers. The research goals are to integrate the data, decipher the biology of these cancers and to identify and validate biomarkers and novel therapeutic targets and to rapidly translate our findings to the clinic. For more information about our research, visit the Oncogenomics Section website.',
          resource_uri: 'https://clinomics.ccr.cancer.gov/clinomics/public/',
          data_content_type: 'Genomics/Omics',
          poc: 'Javed Khan, M.D.',
          poc_email: 'khanjav@mail.nih.gov',
          api: 'https://clinomics.ccr.cancer.gov/clinomics/public/viewProjects',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 1,
          datasets_total: 5,
          data_update_date: '02/23/2024',
        },
        {
          data_resource_id: 'OncoKB',
          resource_name: 'OncoKB',
          resource_type: 'Knowledgebase',
          description: 'OncoKB is a precision oncology knowledge base developed at Memorial Sloan Kettering Cancer Center that contains biological and clinical information about genomic alterations in cancer. Alteration- and tumor type-specific therapeutic implications are classified using the OncoKB Levels of Evidence system, which assigns clinical actionability to individual mutational events.',
          resource_uri: 'https://www.oncokb.org/',
          data_content_type: 'Clinical',
          poc: 'Knowledge Systems group',
          poc_email: 'contact@oncokb.org',
          api: 'https://www.oncokb.org/apiAccess',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 1,
          data_update_date: '03/20/2024',
        },
        {
          data_resource_id: 'OSE',
          resource_name: 'Osteosarcoma Explorer',
          resource_type: 'Analytic Tool',
          description: "Osteosarcoma Explorer (OSE) incorporates a rich array of scientific discoveries for their translation to the care of osteosarcoma patients. The OSE project has assembled a multidisciplinary team of clinical, basic, and data scientists to tackle this rare yet severe disease. In collaboration with Children's Oncology Group and investigators at UT Southwestern, we have integrated clinical data, genomics data, protein data, and pathology images into a well-designed database. Built on this database, our team has developed this user-friendly web portal to offer functionalities such as patient query, online analysis, and digital pathology visualization.",
          resource_uri: 'https://datacommons.swmed.edu/cce/ose/index.php',
          data_content_type: 'Genomics/Omics,Imaging,Clinical',
          poc: 'OSE Mailbox',
          poc_email: 'qbrcsupport@utsouthwestern.edu',
          api: '',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 1,
          data_update_date: '05/22/2024',
        },
        {
          data_resource_id: 'PCAT',
          resource_name: 'PDX for Childhood Cancer Therapeutics',
          resource_type: 'Data Repository',
          description: 'The PDX for Childhood Cancer Therapeutics (PCAT) is a data portal that enables analysis and visualization of pediatric cancer transcriptomes. This portal contains phenotype and genotype data for 324 xenograft models that can be used for testing.  Patient Derived Xenograft (PDX) allow preclinical testing of targeted treatments on tumor cells grafted onto mice.',
          resource_uri: 'http://pedtranscriptome.org/',
          data_content_type: 'Genomics/Omics,Clinical,Xenograft',
          poc: 'Siyuan Zheng',
          poc_email: 'zhengs3@uthscsa.edu',
          api: '',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '12/15/2023',
        },
        {
          data_resource_id: 'PCDC',
          resource_name: 'Pediatric Cancer Data Commons',
          resource_type: 'Data Repository',
          description: 'The Pediatric Cancer Data Commons (PCDC) focuses on collecting, standardizing, and harmonizing disparate sources and types of pediatric cancer clinical research data, including clinical, genomic, and imaging data,   from consortia, research groups, and institutions around the world.',
          resource_uri: 'https://commons.cri.uchicago.edu/pcdc/',
          data_content_type: 'Genomics/Omics,Clinical',
          poc: 'Sam Volchenboum',
          poc_email: 'svolchen@peds.bsd.uchicago.edu',
          api: 'https://portal.pedscommons.org',
          pediatric_specific: 1,
          analytics: 1,
          visualization: 1,
          datasets_total: 5,
          data_update_date: '03/14/2024',
        },
        {
          data_resource_id: 'PDX AIM',
          resource_name: 'Patient-Derived Xenograft and Advanced In Vivo Models',
          resource_type: 'Data Repository',
          description: 'The Patient-Derived Xenograft and Advanced In Vivo Models (PDX-AIM) Core of Baylor College of Medicine is divided into two independent functional units, a PDX Development Unit created to facilitate establishment and use of PDX models using immunocompromised mice as hosts, and an Advanced In Vivo Models Unit created to facilitate establishment and use of patient material grown on the chorioallantoic membrane of the chicken egg (CAM-PDX).',
          resource_uri: 'https://pdxportal.research.bcm.edu/pdxportal/',
          data_content_type: 'Clinical,Xenograft',
          poc: 'Michael Lewis, Ph.D.',
          poc_email: 'mtlewis@bcm.edu',
          api: '',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 1,
          data_update_date: '05/21/2024',
        },
        {
          data_resource_id: 'PDXNet',
          resource_name: 'PDX Development and Trial Centers Research Network',
          resource_type: 'Data Repository',
          description: 'The PDXNet Portal provides a way for researchers to learn about the PDX models, sequencing data (DNA and RNA), and PDX Minimum Information metadata tools generated by the network for public use. The NCI launched the PDX (patient-derived xenografts) Development and Trial Centers Research Network (PDXNet) in September 2017 to accelerate translational research that uses PDX models and sequencing data. The PDXNet includes six PDX Development and Trial Centers and the PDX Data Commons and Coordinating Center. The two PDTCs added in 2018 focus exclusively on developing PDXs from minority patients. PDXNet also works closely with the NCI Patient-Derived Model Repository to ensure data are collected and provided in a standardized format.',
          resource_uri: 'https://portal.pdxnetwork.org/',
          data_content_type: 'Genomics/Omics,Imaging,Clinical,Xenograft',
          poc: 'PDXNet Steering Committee',
          poc_email: 'https://www.pdxnetwork.org/contact',
          api: '',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 2,
          data_update_date: '04/12/2024',
        },
        {
          data_resource_id: 'PEDC',
          resource_name: 'PedcBioPortal for Integrated Childhood Cancer Genomics',
          resource_type: 'Data Repository',
          description: 'PedcBioPortal is an NIH-funded childhood cancer visualization tool modeled upon and partnered with the highly successful, adult-focused, cBioPortal, which was originally developed at Memorial Sloan-Kettering Cancer Center (MSK). PedcBioPortal provides access to high-level processed data types and supports the curation and cross-cancer integration of public, childhood cancer genomic information. PedcBioPortal contains data from 327 studies (as of July 2021). These were all aggregated into a single dataset.',
          resource_uri: 'https://pedcbioportal.kidsfirstdrc.org/',
          data_content_type: 'Genomics/Omics,Clinical',
          poc: 'Ethan Cerami',
          poc_email: 'cerami@jimmy.harvard.edu',
          api: 'https://pedcbioportal.kidsfirstdrc.org/webAPI',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 1,
          data_update_date: '12/18/2023',
        },
        {
          data_resource_id: 'PedMATCH',
          resource_name: 'Pediatric MATCH',
          resource_type: 'Program',
          description: 'NCI-COG Pediatric MATCH (Molecular Analysis for Therapy Choice) is a nationwide cancer treatment clinical trial for children and adolescents, from 1 to 21 years of age, that is testing the use of precision medicine for pediatric cancers. In this trial, patients with solid tumors that are not responding to treatment are assigned to an experimental treatment based on the genetic changes found in their tumors rather than on their type of cancer or cancer site. The genetic changes are found through genomic sequencing, which is a laboratory method used to determine the genetic makeup of cancer cells.',
          resource_uri: 'https://www.cancer.gov/about-cancer/treatment/clinical-trials/nci-supported/pediatric-match',
          data_content_type: 'Genomics/Omics',
          poc: 'Nita Seibel, M.D.',
          poc_email: 'seibelnl@mail.nih.gov ',
          api: '',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '07/25/2024',
        },
        {
          data_resource_id: 'PPTC',
          resource_name: 'Pediatric Preclinical Testing Consortium',
          resource_type: 'Program',
          description: 'The Pediatric Preclinical Testing Consortium (PPTC) is addressing the unmet need of streamlining the development of new therapies for childhood cancers. The PPTC seeks to develop robust biomarkers of anticancer drug activity, and the majority of these are predicted to be genetic mutations that can be detected in tumor DNA and/or RNA. In order to design the most impactful experiments that can be rapidly translated to the clinic, PPTC investigators require a complete genomic characterization of the patient-derived xenograft tumor models that are utilized across the consortium. This will not only allow for the most robust experimental design, but also will increase the engagement of industry partners who seek collaborators poised to provide the proof-of-concept necessary for drugs in their development pipelines.',
          resource_uri: 'https://www.cancer.gov/news-events/cancer-currents-blog/2015/pptc-awards',
          data_content_type: 'Genomics/Omics,Clinical,Xenograft',
          poc: 'Malcolm Smith, M.D., Ph.D.',
          poc_email: 'smithm@ctep.nci.nih.gov',
          api: '',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '12/18/2023',
        },
        {
          data_resource_id: 'PROSPR',
          resource_name: 'Population-based Research to Optimize the Screening Process',
          resource_type: 'Registry',
          description: 'PROSPR (Population-based Research to Optimize the Screening Process) is an NCI-funded research network which includes 10 diverse healthcare delivery systems across the United States. The goal of PROSPR is to better understand how to improve the cancer screening process (recruitment, screening, diagnosis, referral for treatment) in community healthcare settings in the United States. PROSPR is conducting multilevel observational research to evaluate factors that affect the quality and outcomes of the screening processes for cervical, colorectal, and lung cancer. Each PROSPR Research Center conducts organ-specific research, and also participates with other PRCs to conduct trans-PROSPR research projects. The PROSPR Coordinating Center leads the conceptualization and development of measures of health system-level factors that impact the screening processes, as well as measures of screening process quality. These measures are being used in trans-PROSPR research projects.',
          resource_uri: 'https://healthcaredelivery.cancer.gov/prospr/',
          data_content_type: 'Clinical',
          poc: 'NCI PROSPR Team',
          poc_email: 'nciprospr@nih.gov',
          api: '',
          pediatric_specific: 0,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '08/24/2023',
        },
        {
          data_resource_id: 'ScPCA',
          resource_name: 'Single-cell Pediatric Cancer Atlas',
          resource_type: 'Program',
          description: 'The Single-cell Pediatric Cancer Atlas Portal (ScPCA) is a database of uniformly processed single-cell data from pediatric cancer clinical samples and xenografts.',
          resource_uri: 'https://scpca.alexslemonade.org/?utm_source=CCDC&utm_medium=web',
          data_content_type: 'Genomics/Omics',
          poc: 'ScPCA Help Desk',
          poc_email: 'scpca@ccdatalab.org',
          api: '',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 0,
          datasets_total: 18,
          data_update_date: '04/26/2024',
        },
        {
          data_resource_id: 'St. Jude Cloud',
          resource_name: 'St. Jude Cloud',
          resource_type: 'Data Repository',
          description: "St. Jude Cloud, an initiative of St. Jude Children's Research Hospital, provides data and analysis resources to the global research community. Our goal is to empower researchers across the world to advance cures for pediatric cancer and other pediatric catastrophic diseases. Partnering with Microsoft and DNAnexus, our apps are a cohesive blend of comprehensive data, scientific expertise, engineering innovation, and cloud infrastructure.",
          resource_uri: 'https://www.stjude.cloud/',
          data_content_type: 'Genomics/Omics,Clinical,Xenograft',
          poc: 'Clay McLeod ; Jinghui Zhang',
          poc_email: 'Clay.McLeod@stjude.org;jinghui.zhang@stjude.org',
          api: 'https://platform.stjude.cloud/data/diseases',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 16,
          data_update_date: '07/02/2024',
        },
        {
          data_resource_id: 'TARGET',
          resource_name: 'Therapeutically Applicable Research To Generate Effective Treatments',
          resource_type: 'Program',
          description: 'The Therapeutically Applicable Research to Generate Effective Treatments (TARGET) program applies a comprehensive genomic approach to determine molecular changes that drive childhood cancers. The goal of the program is to use data to guide the development of effective, less toxic therapies. TARGET is organized into a collaborative network of disease-specific project teams.',
          resource_uri: 'https://www.cancer.gov/ccg/research/genome-sequencing/target',
          data_content_type: 'Genomics/Omics,Clinical,Xenograft',
          poc: 'Center for Cancer Genomics',
          poc_email: 'NCICCGenomics@mail.nih.gov',
          api: '',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 0,
          datasets_total: 11,
          data_update_date: '05/21/2024',
        },
        {
          data_resource_id: 'TCIA',
          resource_name: 'The Cancer Imaging Archive',
          resource_type: 'Data Repository',
          description: "TCIA is a service which de-identifies and hosts a large archive of medical images of cancer accessible for public download. The data are organized as \"collections\"; typically patients' imaging related by a common disease (e.g. lung cancer), image modality or type (MRI, CT, digital histopathology, etc) or research focus. DICOM is the primary file format used by TCIA for radiology imaging. Supporting data related to the images such as patient outcomes, treatment details, genomics and expert analyses are also provided when available.",
          resource_uri: 'https://www.cancerimagingarchive.net/',
          data_content_type: 'Genomics/Omics,Imaging,Clinical,Xenograft',
          poc: 'TCIA Helpdesk',
          poc_email: 'help@cancerimagingarchive.net',
          api: 'https://www.cancerimagingarchive.net/access-data/',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 18,
          data_update_date: '07/17/2024',
        },
        {
          data_resource_id: 'TCPA',
          resource_name: 'The Cancer Proteome Atlas',
          resource_type: 'Analytic Tool',
          description: 'Functional proteomics represents a powerful approach to rapidly improve our understanding the pathophysiology and therapy of cancer. To facilitate access of the broader research community to cancer proteomics datasets, we have developed a user-friendly data portal, TCPA (The Cancer Proteome Atlas). The current data release mainly consists of TCGA tumor tissue sample sets. TCPA currently provides six modules: Summary, My Protein, Download, Visualization, Analysis and Cell line. Importantly, this resource provides a unique opportunity to validate the findings from TCGA data and identify model cell lines for functional investigation.',
          resource_uri: 'https://tcpaportal.org/tcpa/',
          data_content_type: 'Genomics/Omics',
          poc: 'Dr. Han Liang',
          poc_email: 'hliang1@mdanderson.org',
          api: '',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 1,
          data_update_date: '06/13/2024',
        },
        {
          data_resource_id: 'Texas KidsCanSeq',
          resource_name: 'Texas KidsCanSeq',
          resource_type: 'Program',
          description: "The Texas KidsCanSeq Study is part of the Clinical Sequencing Evidence-Generating Research (CSER) consortium funded by the NIH National Human Genome Research Institute. The goal of the study is to integrate genomic sequence information into the care of childhood cancer patients with high-risk solid tumors and brain tumors. In conjunction with Texas Children's Cancer Center and BCM's Whole Genome Laboratory, KidsCanSeq assesses the utility of exome sequence (ES) testing compared to more targeted methods in pediatric cancer patients.",
          resource_uri: 'https://www.bcm.edu/academic-centers/medical-ethics-and-health-policy/research/elsi-genomics-research/texas-kidscanseq',
          data_content_type: 'Genomics/Omics',
          poc: 'Sharon Plon MD, PhD',
          poc_email: 'splon@bcm.edu',
          api: '',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '02/23/2024',
        },
        {
          data_resource_id: 'TPC-DTC_PIVOT',
          resource_name: 'Texas Pediatric Cancer Drug Testing Core & Pediatric Preclinical In Vivo Testing Consortium',
          resource_type: 'Program',
          description: 'The Pediatric Preclinical In Vivo Testing consortium (PIVOT) provides rigorous preclinical testing of novel molecularly targeted agents using in vivo models of pediatric cancer.  PIVOT is an extension and expansion of two previous, highly successful NCI programs: Pediatric Preclinical Testing Program (<a href="https://ctep.cancer.gov/content/docs/PPTP_Overview.pdf" target="_blank" rel="noreferrer noopener">PPTP</a>; 2004-2014) and Pediatric Preclinical Testing Consortium (<a href="https://www.cancer.gov/news-events/cancer-currents-blog/2015/pptc-awards" target="_blank" rel="noreferrer noopener">PPTC</a>; 2015-2021). The objective of the CPRIT (Cancer Prevention and Research Institute of Texas) supported <a href="https://tpc-dtc.uthscsa.edu/" target="_blank" rel="noreferrer noopener">TPC-DTC</a> is to provide reproducible high-quality in vivo data to guide pediatric clinical development of novel agents and combinations. Both initiatives have developed within the context of the Research to Accelerate Cures and Equity for Children Act (<a href="https://www.congress.gov/bill/115th-congress/house-bill/1231" target="_blank" rel="noreferrer noopener">RACE for Children Act</a>). For preclinical testing, this necessitates having sufficient models with the appropriate genetic alterations in the context of the appropriate childhood cancer types. The RACE Act requires the FDA to develop a list of molecular targets of known and new drugs/biologics. If agents are determined to be substantially relevant to the growth and progression of pediatric cancer, this may trigger the requirement for pediatric investigations. This expectation applies both to drugs/biologics being developed by Pharma and by academic centers.',
          resource_uri: 'https://tpc-dtc.uthscsa.edu/;https://preclinicalpivot.org/',
          data_content_type: 'Xenograft,Cell Lines',
          poc: 'Raushan Kurmasheva, PhD',
          poc_email: 'kurmasheva@uthscsa.edu',
          api: '',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '08/23/2023',
        },
        {
          data_resource_id: 'Treehouse',
          resource_name: 'Treehouse Childhood Cancer Initiative',
          resource_type: 'Data Repository',
          description: "The Treehouse Childhood Cancer Initiative at the UC Santa Cruz Genomics Institute uses shared data to analyze a child's tumor against both child and adult patient cancer tumors. As part of our research, we have collected data shared from more than 11,000 tumor samples and made it freely available for to researchers everywhere to download and for visualization. This gene expression data is available along with patient-privacy protected clinical data, including age, gender, and disease type.",
          resource_uri: 'https://treehousegenomics.soe.ucsc.edu/',
          data_content_type: 'Genomics/Omics,Clinical,Xenograft',
          poc: 'Olena Vaske',
          poc_email: 'olena@ucsc.edu',
          api: '',
          pediatric_specific: 1,
          analytics: 1,
          visualization: 1,
          datasets_total: 8,
          data_update_date: '04/15/2024',
        },
        {
          data_resource_id: 'VIVO',
          resource_name: 'VIVO Biobank',
          resource_type: 'Biorepository',
          description: "We are the UK's leading research resource dedicated to storing samples and data of cancers affecting children and young people. We unite researchers, medical professionals, patients, partners, donors, and charities - all with one goal in mind: to push the boundaries of research into childhood and youth cancers. VIVO Biobank is a collaboration between Cancer Research UK and Blood Cancer UK.",
          resource_uri: 'https://vivobiobank.org/',
          data_content_type: 'Biospecimens',
          poc: 'Contact Email',
          poc_email: 'enquiries@vivobiobank.org',
          api: '',
          pediatric_specific: 1,
          analytics: 0,
          visualization: 0,
          datasets_total: 1,
          data_update_date: '08/03/2023',
        },
        {
          data_resource_id: 'Vizome',
          resource_name: 'Vizome',
          resource_type: 'Analytic Tool',
          description: 'Vizome is an interactive, context-aware knowledge discovery platform created by Libbey White, Beth Wilmot, Dan Bottomly, and Shannon McWeeney at Oregon Health & Science University.',
          resource_uri: 'http://vizome.org/',
          data_content_type: 'Genomics/Omics,Clinical',
          poc: 'Vizome Team',
          poc_email: 'vizome@ohsu.edu',
          api: '',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 3,
          data_update_date: '11/21/2023',
        },
        {
          data_resource_id: 'VPCC',
          resource_name: 'Victorian Paediatric Cancer Consortium',
          resource_type: 'Data Repository',
          description: "We are some of Victoria's leading research, academic and clinical organisations, working together to make things better for children and adolescents with cancer through world-class medical research and innovation. This work demands that we harness cutting-edge technology and methods. Together, the VPCC's researchers, doctors, and families of kids with cancer can deliver research with real-world impact, better medical care, and improved training for the researchers and clinicians of the future. The VPCC was made possible thanks to the tireless efforts of the Children's Cancer Foundation and funding from the Australian Government's Medical Research Future Fund (MRFF). Our partnership organisations are The Royal Children's Hospital (RCH), Monash Children's Hospital (MCH), Hudson Institute of Medical Research, Murdoch Children's Research Institute (MCRI), Monash University, University of Melbourne, Peter MacCallum Cancer Centre, Walter and Eliza Hall Institute of Medical Research (WEHI) and the Children's Cancer Foundation. Childhood cancer investigators from these organisations have joined forces to drive impactful and interdisciplinary research, improve medical care, and train the childhood cancer leaders of tomorrow. The VPCC partnerships span discovery research and clinical innovation programs; integrated biobanking, data management and bioinformatics platforms; and capacity building for training the next generation of researchers and clinicians, annual scientific symposia and educational events.",
          resource_uri: 'https://vicpcc.org.au/',
          data_content_type: 'Genomics/Omics,Cell Lines',
          poc: 'Naama Neeman',
          poc_email: 'Naama.Neeman@hudson.org.au',
          api: '',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 1,
          data_update_date: '04/16/2024',
        },
        {
          data_resource_id: 'WHO-IARC',
          resource_name: 'World Health Organization - International Agency for Research on Cancer',
          resource_type: 'Program',
          description: 'The International Agency for Research on Cancer (IARC) is the specialized cancer agency of the World Health Organization. The objective of IARC is to promote international collaboration in cancer research. The Agency is interdisciplinary, bringing together skills in epidemiology, laboratory sciences, and biostatistics to identify the causes of cancer so that preventive measures may be adopted and the burden of disease and associated suffering reduced. A significant feature of the Agency is its expertise in coordinating research across countries and organizations; its independent role as an international organization facilitates this activity. IARC has a particular interest in conducting research in low- and middle-income countries through partnerships and collaborations with researchers in these regions.',
          resource_uri: 'https://www.iarc.who.int/',
          data_content_type: 'Clinical',
          poc: 'Contact Email',
          poc_email: 'ccs@iarc.fr',
          api: '',
          pediatric_specific: 0,
          analytics: 0,
          visualization: 0,
          datasets_total: 4,
          data_update_date: '05/03/2024',
        },
        {
          data_resource_id: 'Xena Browser',
          resource_name: 'Xena Browser',
          resource_type: 'Analytic Tool',
          description: 'University California Santa Cruz (UCSC) Xena allows users to explore functional genomic data sets for correlations between genomic and/or phenotypic variables.',
          resource_uri: 'https://xenabrowser.net/',
          data_content_type: 'Genomics/Omics',
          poc: 'Xena Browser Contact Email',
          poc_email: 'genome-cancer@soe.ucsc.edu',
          api: 'https://ucsc-xena.gitbook.io/project/overview-of-features/accessing-data-through-python ; https://ucsc-xena.gitbook.io/project/overview-of-features/download-data',
          pediatric_specific: 0,
          analytics: 1,
          visualization: 1,
          datasets_total: 1,
          data_update_date: '04/12/2024',
        },
      ],
    },
  };

  return connect(mapStateToProps, mapDispatchToProps)(Filters);
})();

export default ReduxFilters;
